### ISSUE TITLE
StreamingFileSink.forBulkFormat enableCheckPoint

### ISSUE THREAD

**Issue by wuguanyu** [tencentyun/flink-cos-fs#10]
at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:241) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:162) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:371) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointStreamOperator(SubtaskCheckpointCoordinatorImpl.java:686) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.buildOperatorSnapshotFutures(SubtaskCheckpointCoordinatorImpl.java:607) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:572) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:298) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$9(StreamTask.java:1004) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:988) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpoint(StreamTask.java:912) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	... 10 more
Caused by: org.apache.flink.util.SerializedThrowable: The stream has been closed.
	at org.apache.flink.fs.cos.common.utils.RefCountedFile.requiredOpened(RefCountedFile.java:93) ~[?:?]
	at org.apache.flink.fs.cos.common.utils.RefCountedFile.write(RefCountedFile.java:73) ~[?:?]
	at org.apache.flink.fs.cos.common.utils.RefCountedBufferingFileStream.flush(RefCountedBufferingFileStream.java:103) ~[?:?]
	at org.apache.flink.fs.cos.common.writer.COSRecoverableFsDataOutputStream.closeAndUploadPart(COSRecoverableFsDataOutputStream.java:160) ~[?:?]
	at org.apache.flink.fs.cos.common.writer.COSRecoverableFsDataOutputStream.closeForCommit(COSRecoverableFsDataOutputStream.java:93) ~[?:?]
	at org.apache.flink.streaming.api.functions.sink.filesystem.OutputStreamBasedPartFileWriter.closeForCommit(OutputStreamBasedPartFileWriter.java:62) ~[flink-table-blink_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.BulkPartWriter.closeForCommit(BulkPartWriter.java:62) ~[flink-table-blink_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.closePartFile(Bucket.java:262) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.prepareBucketForCheckpointing(Bucket.java:304) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.Bucket.onReceptionOfCheckpoint(Bucket.java:276) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.Buckets.snapshotActiveBuckets(Buckets.java:270) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.Buckets.snapshotState(Buckets.java:261) ~[flink-dist_2.12-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.functions.sink.filesystem.StreamingFileSinkHelper.snapshotState(StreamingFileSinkHelper.java:87) ~[flink-dist_2.12-1.12.2.jar:1.12.2]

**Comment by wuguanyu** [comment]
2022-04-20 15:45:51,072 INFO  org.apache.flink.fs.cos.common.utils.RefCountedBufferingFileStream [] - begin to close the file: org.apache.flink.fs.cos.common.utils.RefCountedFile@62b86ecf. 2022-04-20 15:45:51,076 INFO  org.apache.flink.fs.cos.common.utils.RefCountedBufferingFileStream [] - begin to flush the buffer to the file: org.apache.flink.fs.cos.common.utils.RefCountedFile@62b86ecf.
